import 'package:flutter/material.dart';

/// These are not constants but used frequently.
double kWidth(BuildContext context) => MediaQuery.of(context).size.width;

double kHeight(BuildContext context) => MediaQuery.of(context).size.height;

const kPrimaryColor = Color(0xffFFFFFF);
const kGreyColor = Color(0xff707070);
const kPostBackground = Color(0xffF2F2F2);
const kLightGreyColor = Color(0xffE0E0E0);
const kGreyColor2 = Color(0xff747272);
const kGreyColor3 = Color(0xffC4C4C4);
const kDarkGreyColor = Color(0xff434343);
const kBlackColor = Color(0xff373131);
const kRedColor = Color(0xffEF8484);
const kGreenColor = Colors.green;
const kOrangeColor = Color(0xffFFB57F);
Color kBorderColor = const Color(0xff959595).withOpacity(0.51);

List identifyMySelf = [
  'Male',
  'Female',
  'Non-binary',
];
List interestedIn = [
  'Male',
  'Female',
  'Both',
];
List yearOfStudy = [
  'Joining in september',
  '1st',
  '2nd',
  '3rd',
  '4th',
];
List<String> light = [
  "Single",
  "It's complicated",
  "In a relationship"
];
final List<Color> lights = [
  kRedColor,
  kGreenColor,
  kOrangeColor,
];

final List<String> universities = [
  "University of Aberdeen",
  "Abertay University",
  "Aberystwyth University",
  "Anglia Ruskin University",
  "Aston University",
  "Bangor University",
  "University of Bath",
  "Bath Spa University",
  "University of Bedfordshire",
  "University of Birmingham",
  "Birmingham City University",
  "University College Birmingham",
  "Bishop Grosseteste University",
  "University of Bolton",
  "The Arts University Bournemouth",
  "Bournemouth University",
  "BPP University",
  "University of Bradford",
  "University of Brighton",
  "University of Bristol",
  "Brunel University",
  "University of Buckingham",
  "Buckinghamshire New University",
  "University of Cambridge",
  "Canterbury Christ Church University",
  "Cardiff Metropolitan University",
  "Cardiff University",
  "University of Chester",
  "University of Chichester",
  "Coventry University",
  "Cranfield University",
  "University for the Creative Arts",
  "University of Cumbria",
  "De Montfort University",
  "University of Derby",
  "University of Dundee",
  "Durham Castle",
  "Durham University",
  "University of East Anglia",
  "University of East London",
  "Edge Hill University",
  "University of Edinburgh",
  "Edinburgh Napier University",
  "University of Essex",
  "University of Exeter",
  "Falmouth University",
  "University of Glasgow",
  "Glasgow Caledonian University",
  "University of Gloucestershire,",
  "University of Greenwich",
  "Harper Adams University",
  "Hartpury University",
  "Heriot-Watt University",
  "University of Hertfordshire",
  "University of the Highlands & Islands,",
  "University of Huddersfield",
  "University of Hull",
  "Imperial College London",
  "Keele University",
  "University of Kent",
  "Kingston University",
  "University of Central Lancashire",
  "Lancaster University",
  "University of Leeds",
  "Leeds Arts University",
  "Leeds Beckett University",
  "Leeds Trinity University",
  "Leeds Conservatoire",
  "University of Leicester",
  "University of Lincoln",
  "University of Liverpool",
  "Liverpool Hope University",
  "Liverpool John Moores University",
  "University of London",
  "London Metropolitan University",
  "London South Bank University",
  "Loughborough University",
  "University of Manchester",
  "Manchester Metropolitan University",
  "Middlesex University",
  "Newcastle University",
  "Newman University",
  "University of Northampton",
  "Northumbria University",
  "Norwich University of the Arts",
  "University of Nottingham",
  "Nottingham Trent University",
  "The Open University",
  "University of Oxford",
  "Oxford Brookes University",
  "Plymouth Marjon University",
  "University of Plymouth",
  "University of Portsmouth",
  "Queen Margaret University",
  "Queen's University Belfast",
  "Ravensbourne University London",
  "University of Reading",
  "Regent's University London",
  "The Robert Gordon University",
  "Roehampton University",
  "Royal Agricultural University",
  "University of Salford",
  "University of Sheffield",
  "Sheffield Hallam University",
  "University of South Wales",
  "University of Southampton",
  "Solent University",
  "University of St Andrews",
  "St Mary's University",
  "Staffordshire University",
  "University of Stirling",
  "University of Strathclyde",
  "University of Suffolk",
  "University of Sunderland",
  "University of Surrey",
  "University of Sussex",
  "Swansea University",
  "Teesside University",
  "University of the Arts London",
  "Ulster University",
  "University of Law",
  "University of Wales",
  "University of Wales",
  "University of Warwick",
  "University of the West of England",
  "University of the West of Scotland",
  "University of West London",
  "University of Westminster",
  "University of Winchester",
  "University of Wolverhampton",
  "University of Worcester",
  "Wrexham Glyndŵr University",
  "University of York",
  "York St John University",
];
